<?php

return [
    'state_corporations' => [
    'Science Research and Innovation',
    'Internal Security and National Administration',
    'Correctional Services',
    'Defence',
    'National Treasury',
    'Public Investments and Assets Management',
    'Economic Planning',
    'Public Service and Human Capital Development',
    'Roads',
    'Transport',
    'Aviation and Aerospace Development',
    'Lands and Physical Planning',
    'Broadcasting and Telecommunications',
    'ICT and The Digital Economy',
    'Medical Services',
    'Public Health and Professional Standards',
    'Basic Education',
    'Technical, Vocational Education and Training (TVET)',
    'Higher Education and Research',
    'Agriculture',
    'Livestock Development',
    'Investment Promotions',
    'Industry',
    'Trade',
    'Micro, Small, Medium Enterprises (MSME) Development',
    'Youth Affairs and Creative Economy',
    'Sports',
    'Environment and Climate Change',
    'Forestry',
    'Wildlife',
    'Gender and Affirmative Action',
    'Culture, the Arts & Heritage',
    'Children Services',
    'Water and Sanitation',
    'Irrigation',
    'Energy',
    'Petroleum',
    'Social Protection and Senior Citizen Affairs',
    'Labour',
    'The Blue Economy and Fisheries',
    'Mining',
    'Shipping and Maritime Affairs',
    'Justice, Human Rights & Constitutional Affairs',
    'The State Law Office'
    ],
];