<?php

return [
    'state_corporations' => [
        'University Fund',
        'Higher Education Loans Board',
        'Kenya Tourism Board',
        'Tourism Research Institute',
        'Export Processing Zones Authority',
        'Special Economic Zones Authority',
        'Anti-Counterfeit Authority',
        'Kenya Industrial Property Institute',
        'Kenya Copyright Board',
        'Kenya Industrial Research and Development Institute',
        'Kenya Industrial Estates',
        'Agricultural Finance Corporation',
        'Commodities Fund',
        'Kenya Forest Service',
        'Kenya Water Towers Agency',
        'Agricultural Development Corporation',
        'Kenya Animal Genetic Resource Centre',
        'National Irrigation Authority',
        'National Water Harvesting and Storage Authority',
        'Kenya Law Reform Commission',
        'National Council for Law Reporting',
        'Tourism Promotion Fund',
        'Tourism Fund',
        'Commission for University Education',
        'Technical and Vocational Education and Training Authority',
        'Kenya National Qualifications Authority',
        'Kenya Rural Roads Authority',
        'Kenya Urban Roads Authority',
        'Kenya Investment Authority',
        'Kenya Export Promotion and Branding Agency',
        'Water Services Regulatory Board',
        'Water Regulatory Authority',
        'Regional Center on Ground Water Resources, Education, Training and Research',
    ],
];